version: 1.0.{build}
branches:
  only:
  - master
before_build:
- cmd: nuget restore ./Visions/Visions.sln
build:
  project: ./Visions/Visions.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal