//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Constants", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visions lets you effortlessly share anything..
        /// </summary>
        public static string AboutPageMainText {
            get {
                return ResourceManager.GetString("AboutPageMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post text, photos, quotes, links, music, and videos from your browser, phone, desktop or wherever you happen to be..
        /// </summary>
        public static string AboutPageSecondaryText {
            get {
                return ResourceManager.GetString("AboutPageSecondaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTabText {
            get {
                return ResourceManager.GetString("AboutTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string AdminManageSectionTitle {
            get {
                return ResourceManager.GetString("AdminManageSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string ArticleContentPlaceholderMessage {
            get {
                return ResourceManager.GetString("ArticleContentPlaceholderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text must be more than {0} characters long..
        /// </summary>
        public static string ArticleFieldMinLengthValidationMessage {
            get {
                return ResourceManager.GetString("ArticleFieldMinLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter some text..
        /// </summary>
        public static string ArticleFiledRequiredValidationMessage {
            get {
                return ResourceManager.GetString("ArticleFiledRequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ArticleTitlePlaceholderMessage {
            get {
                return ResourceManager.GetString("ArticleTitlePlaceholderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to homepage.
        /// </summary>
        public static string BackToHomepageMessage {
            get {
                return ResourceManager.GetString("BackToHomepageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string BackToListMessage {
            get {
                return ResourceManager.GetString("BackToListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a photo.
        /// </summary>
        public static string ChoosePhotoAltMessage {
            get {
                return ResourceManager.GetString("ChoosePhotoAltMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string DeleteConfirmationQuestionMessage {
            get {
                return ResourceManager.GetString("DeleteConfirmationQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete photo.
        /// </summary>
        public static string DeletePhotoTitle {
            get {
                return ResourceManager.GetString("DeletePhotoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteSectionText {
            get {
                return ResourceManager.GetString("DeleteSectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DetailsSectionText {
            get {
                return ResourceManager.GetString("DetailsSectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButtonText {
            get {
                return ResourceManager.GetString("EditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit failed.
        /// </summary>
        public static string EditFailedMessage {
            get {
                return ResourceManager.GetString("EditFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit photo.
        /// </summary>
        public static string EditPhotoTitle {
            get {
                return ResourceManager.GetString("EditPhotoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string EditSaveButtonText {
            get {
                return ResourceManager.GetString("EditSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditSectionText {
            get {
                return ResourceManager.GetString("EditSectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit successful.
        /// </summary>
        public static string EditSuccessfulMessage {
            get {
                return ResourceManager.GetString("EditSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET MVC - Course project.
        /// </summary>
        public static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founded.
        /// </summary>
        public static string FoundedByLabel {
            get {
                return ResourceManager.GetString("FoundedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March 2017.
        /// </summary>
        public static string FoundedByText {
            get {
                return ResourceManager.GetString("FoundedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder.
        /// </summary>
        public static string FounderLabel {
            get {
                return ResourceManager.GetString("FounderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Unicorn.
        /// </summary>
        public static string FounderText {
            get {
                return ResourceManager.GetString("FounderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string HomepageGetStartedButtonText {
            get {
                return ResourceManager.GetString("HomepageGetStartedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Come for what you love..
        /// </summary>
        public static string HomepageMainText {
            get {
                return ResourceManager.GetString("HomepageMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay for what you discover..
        /// </summary>
        public static string HomepageSecondaryText {
            get {
                return ResourceManager.GetString("HomepageSecondaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string LabelForImage {
            get {
                return ResourceManager.GetString("LabelForImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visions..
        /// </summary>
        public static string LogoText {
            get {
                return ResourceManager.GetString("LogoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogoutTabText {
            get {
                return ResourceManager.GetString("LogoutTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MenuTabText {
            get {
                return ResourceManager.GetString("MenuTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        public static string NoResultsMessage {
            get {
                return ResourceManager.GetString("NoResultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo details.
        /// </summary>
        public static string PhotoDetailsTitle {
            get {
                return ResourceManager.GetString("PhotoDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string PostArticleButtonText {
            get {
                return ResourceManager.GetString("PostArticleButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got something to say?.
        /// </summary>
        public static string PostArticleTitle {
            get {
                return ResourceManager.GetString("PostArticleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string PostUploadedPhotoButtonText {
            get {
                return ResourceManager.GetString("PostUploadedPhotoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfileTabText {
            get {
                return ResourceManager.GetString("ProfileTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchPlaceholderText {
            get {
                return ResourceManager.GetString("SearchPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared dashboard.
        /// </summary>
        public static string SharedDashboardTitle {
            get {
                return ResourceManager.GetString("SharedDashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        public static string SharedTabText {
            get {
                return ResourceManager.GetString("SharedTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags, separated by spaces, at least two characters long.
        /// </summary>
        public static string TagsFieldPlaceholderMessage {
            get {
                return ResourceManager.GetString("TagsFieldPlaceholderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle navigation.
        /// </summary>
        public static string ToggleNavigationText {
            get {
                return ResourceManager.GetString("ToggleNavigationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed.
        /// </summary>
        public static string UploadFailedMessage {
            get {
                return ResourceManager.GetString("UploadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload photo.
        /// </summary>
        public static string UploadPhotoTitle {
            get {
                return ResourceManager.GetString("UploadPhotoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload successful.
        /// </summary>
        public static string UploadSuccessfulMessage {
            get {
                return ResourceManager.GetString("UploadSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserIdDisplayName {
            get {
                return ResourceManager.GetString("UserIdDisplayName", resourceCulture);
            }
        }
    }
}
